export type Category = "universitaria" | "club" | "evento" | "rave";

export type Tier = "aberto" | "verificado" | "solo" | "oficial";

export type League = "universitaria" | "clubs" | "coletivos";

export type OrganizerType = "atletica" | "liga" | "club" | "coletivo" | "produtora";

export type Organizer = {
  slug: string;
  name: string;
  league: League;
  type: OrganizerType;
  city?: string;
  description?: string;
  foundedYear?: number;
  image?: string;
};

export type Party = {
  id: string;
  slug: string;
  name: string;
  university: string; // legado: nome do org/venue/aberto — mantido pra compat com ranking atual
  category: Category;
  date: string;
  location: string;
  address: string;
  image: string;
  price: number;
  votes: number;
  rating: number;
  attendees: number;
  tags: string[];
  description: string;
  organizer: string; // legado: nome do organizador (string solta)
  organizerSlug: string; // novo: liga com tabela `organizers`
  tier: Tier; // novo: aberto/verificado/oficial
  theme: string;
};

export const categoryMeta: Record<Category, { label: string; color: string }> = {
  universitaria: { label: "universitária", color: "from-violet-500 to-fuchsia-500" },
  club: { label: "club", color: "from-pink-500 to-orange-500" },
  evento: { label: "evento", color: "from-cyan-500 to-blue-500" },
  rave: { label: "rave", color: "from-emerald-500 to-teal-500" },
};

export const tierMeta: Record<Tier, { label: string; color: string; description: string }> = {
  aberto: {
    label: "Aberta",
    color: "from-white/30 to-white/10",
    description: "Festa indexada pelo PartyRank — info pública, sem parceria comercial.",
  },
  verificado: {
    label: "Verificada",
    color: "from-cyan-400 to-blue-500",
    description: "Organizador reivindicou a página e mantém os dados oficiais. Grátis.",
  },
  solo: {
    label: "Solo",
    color: "from-rose-400 to-pink-500",
    description:
      "Pra quem organiza festa sozinho. Vende ingresso pelo PartyRank, página oficial, sem o pacote PRO completo.",
  },
  oficial: {
    label: "Oficial",
    color: "from-amber-400 to-yellow-500",
    description: "Festa parceira PartyRank. Vende ingresso pela plataforma e tem acesso à área PRO.",
  },
};

export const leagueMeta: Record<League, { label: string; short: string; color: string; description: string }> = {
  universitaria: {
    label: "Liga Universitária",
    short: "Universitária",
    color: "from-violet-500 to-fuchsia-500",
    description: "Atléticas e ligas das principais faculdades de SP — USP, Insper, FGV, Mack, PUC e mais.",
  },
  clubs: {
    label: "Liga dos Clubs",
    short: "Clubs",
    color: "from-pink-500 to-orange-500",
    description: "Casas noturnas e venues que pautam a noite paulistana — Audio, D-Edge, Warung e mais.",
  },
  coletivos: {
    label: "Liga dos Coletivos",
    short: "Coletivos",
    color: "from-emerald-400 to-teal-500",
    description: "Produtoras e coletivos de festa, rave e cultura eletrônica — NEON, Tribe, T4F e mais.",
  },
};

export const organizers: Organizer[] = [
  // ===== LIGA UNIVERSITÁRIA =====
  {
    slug: "atletica-usp",
    name: "Atlética USP",
    league: "universitaria",
    type: "atletica",
    city: "São Paulo",
    description: "Atlética da Universidade de São Paulo. Sede da Noite Colorida e calouradas históricas.",
    foundedYear: 1934,
  },
  {
    slug: "liga-insper",
    name: "Liga Insper",
    league: "universitaria",
    type: "liga",
    city: "São Paulo",
    description: "Liga atlética do Insper, organiza o Carnaval Insper e a temporada universitária da escola.",
    foundedYear: 2004,
  },
  {
    slug: "atletica-fgv",
    name: "Atlética FGV",
    league: "universitaria",
    type: "atletica",
    city: "São Paulo",
    description: "Por trás da White Party e das festas premium do calendário universitário.",
    foundedYear: 1970,
  },
  {
    slug: "atletica-mackenzie",
    name: "Atlética Mackenzie",
    league: "universitaria",
    type: "atletica",
    city: "São Paulo",
    description: "Pool parties e festas de funk que viraram marca da Mackenzie.",
    foundedYear: 1952,
  },
  {
    slug: "atletica-puc",
    name: "Atlética PUC-SP",
    league: "universitaria",
    type: "atletica",
    city: "São Paulo",
    description: "Calouradas, neon e a cara mais cultural do circuito universitário.",
    foundedYear: 1946,
  },
  {
    slug: "atletica-espm",
    name: "Atlética ESPM",
    league: "universitaria",
    type: "atletica",
    city: "São Paulo",
    description: "Festas com identidade visual forte — comunicação cuida da pista.",
    foundedYear: 1995,
  },

  // ===== LIGA DOS CLUBS =====
  {
    slug: "audio-club",
    name: "Audio Club",
    league: "clubs",
    type: "club",
    city: "Barra Funda",
    description: "Maior club de SP. Headliner internacional toda semana, estrutura de arena.",
  },
  {
    slug: "d-edge",
    name: "D-Edge",
    league: "clubs",
    type: "club",
    city: "Barra Funda",
    description: "Reduto techno mais fiel da cidade. Curadoria dos residentes é referência.",
  },
  {
    slug: "warung-sp",
    name: "Warung SP",
    league: "clubs",
    type: "club",
    city: "Vila Madalena",
    description: "Filial paulistana do clássico de Itajaí. Quinta de underground na Vila.",
  },
  {
    slug: "villa-mix",
    name: "Villa Mix VO",
    league: "clubs",
    type: "club",
    city: "Vila Olímpia",
    description: "Casa de samba, pagode e happy hour referência da Vila Olímpia.",
  },
  {
    slug: "fabrique",
    name: "Fabrique Club",
    league: "clubs",
    type: "club",
    city: "Barra Funda",
    description: "Hip-hop, rap e cena urbana — um dos clubes mais autorais da cidade.",
  },

  // ===== LIGA DOS COLETIVOS =====
  {
    slug: "neon-productions",
    name: "NEON Productions",
    league: "coletivos",
    type: "produtora",
    city: "São Paulo",
    description: "Produtora do NEON Fest e festivais grandes em arenas paulistas.",
  },
  {
    slug: "tribe-collective",
    name: "Tribe Collective",
    league: "coletivos",
    type: "coletivo",
    city: "São Paulo",
    description: "Coletivo de raves open-air, trance e cultura outdoor.",
  },
  {
    slug: "t4f",
    name: "T4F",
    league: "coletivos",
    type: "produtora",
    city: "São Paulo",
    description: "Produtora de afters e eventos paralelos a grandes festivais.",
  },
  {
    slug: "mamba-negra",
    name: "Mamba Negra",
    league: "coletivos",
    type: "coletivo",
    city: "São Paulo",
    description: "Coletivo de festa underground com estética e curadoria muito próprias.",
  },
];

/**
 * Returns an ISO date offset N days from today (UTC midnight). Lets a few of
 * the mock parties stay "current" relative to whatever day the site renders,
 * so the live/tonight/tomorrow badges actually show up in development. When
 * we wire up the real DB, this whole helper goes away.
 */
function inDays(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export const parties: Party[] = [
  // ===== UNIVERSITÁRIAS =====
  {
    id: "1",
    slug: "noite-colorida-usp",
    name: "Noite Colorida",
    university: "USP",
    category: "universitaria",
    date: inDays(0),
    location: "Casa Natura Musical",
    address: "Rua Artur de Azevedo, 2134 - Pinheiros",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1600&q=80",
    price: 8000,
    votes: 1842,
    rating: 4.9,
    attendees: 1200,
    tags: ["open bar", "eletrônica", "tematica"],
    description:
      "A festa que colore a noite de São Paulo. Line-up com os melhores DJs, estrutura de arena e open bar completo até 3h da manhã.",
    organizer: "Atlética USP",
    organizerSlug: "atletica-usp",
    tier: "oficial",
    theme: "Rainbow",
  },
  {
    id: "2",
    slug: "carnaval-insper",
    name: "Carnaval Insper",
    university: "Insper",
    category: "universitaria",
    date: inDays(1),
    location: "Audio Club",
    address: "Av. Francisco Matarazzo, 694",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1600&q=80",
    price: 12000,
    votes: 1654,
    rating: 4.8,
    attendees: 2000,
    tags: ["samba", "axé", "bloco"],
    description:
      "O carnaval oficial do Insper chegou. Blocos, axé, samba e muito confete. A maior concentração universitária da cidade.",
    organizer: "Liga Insper",
    organizerSlug: "liga-insper",
    tier: "oficial",
    theme: "Carnaval",
  },
  {
    id: "3",
    slug: "white-party-fgv",
    name: "White Party FGV",
    university: "FGV",
    category: "universitaria",
    date: inDays(3),
    location: "Clube Hípico",
    address: "Av. Pedro Álvares Cabral, 1301",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1600&q=80",
    price: 15000,
    votes: 1421,
    rating: 4.7,
    attendees: 1500,
    tags: ["premium", "eletrônica", "rooftop"],
    description:
      "Dress code branco. Rooftop, piscina e line-up internacional. A festa mais aguardada do semestre.",
    organizer: "Atlética FGV",
    organizerSlug: "atletica-fgv",
    tier: "oficial",
    theme: "All White",
  },
  {
    id: "4",
    slug: "pool-party-mackenzie",
    name: "Pool Party Mack",
    university: "Mackenzie",
    category: "universitaria",
    date: inDays(6),
    location: "Villa Country",
    address: "R. Belchior de Azevedo, 150",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&q=80",
    price: 6000,
    votes: 1203,
    rating: 4.6,
    attendees: 900,
    tags: ["piscina", "funk", "verão"],
    description:
      "Piscina aquecida, DJs do funk e hit parade. A pool party que não pode faltar na agenda universitária.",
    organizer: "Atlética Mackenzie",
    organizerSlug: "atletica-mackenzie",
    tier: "oficial",
    theme: "Summer",
  },
  {
    id: "5",
    slug: "calourada-puc",
    name: "Calourada PUC",
    university: "PUC-SP",
    category: "universitaria",
    date: inDays(10),
    location: "Clube Paineiras",
    address: "Av. Dr. Arnaldo, 1565",
    image: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=1600&q=80",
    price: 5000,
    votes: 1098,
    rating: 4.5,
    attendees: 1100,
    tags: ["calouros", "funk", "sertanejo"],
    description:
      "Recebendo os calouros com a maior festa do ano. Três pistas, food trucks e área open até 4h.",
    organizer: "Atlética PUC",
    organizerSlug: "atletica-puc",
    tier: "verificado",
    theme: "Neon",
  },
  {
    id: "13",
    slug: "fgv-tropical",
    name: "FGV Tropical",
    university: "FGV",
    category: "universitaria",
    date: "2026-04-12",
    location: "Audio Club",
    address: "Av. Francisco Matarazzo, 694",
    image: "https://images.unsplash.com/photo-1581974944026-5d6ed762f617?w=1600&q=80",
    price: 11000,
    votes: 1287,
    rating: 4.6,
    attendees: 1400,
    tags: ["tropical", "eletrônica", "open bar"],
    description: "Edição tropical da Atlética FGV. Praia indoor, decoração imersiva e open bar até 4h.",
    organizer: "Atlética FGV",
    organizerSlug: "atletica-fgv",
    tier: "oficial",
    theme: "Tropical",
  },
  {
    id: "14",
    slug: "fgv-rooftop-summer",
    name: "Rooftop Summer FGV",
    university: "FGV",
    category: "universitaria",
    date: "2026-03-08",
    location: "Skye Bar",
    address: "Av. Brg. Luís Antônio, 4700",
    image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1600&q=80",
    price: 14000,
    votes: 940,
    rating: 4.8,
    attendees: 700,
    tags: ["rooftop", "premium", "house"],
    description: "Aniversário da Atlética FGV no rooftop mais alto da cidade.",
    organizer: "Atlética FGV",
    organizerSlug: "atletica-fgv",
    tier: "oficial",
    theme: "Rooftop",
  },
  {
    id: "15",
    slug: "usp-ressaca",
    name: "Ressaca USP",
    university: "USP",
    category: "universitaria",
    date: "2026-04-26",
    location: "Tom Brasil",
    address: "Rua Bragança Paulista, 1281",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&q=80",
    price: 7000,
    votes: 1322,
    rating: 4.5,
    attendees: 1300,
    tags: ["after", "axé", "samba"],
    description: "A festa que segura a galera no domingão. Ressaca da Noite Colorida com line-up de samba e axé.",
    organizer: "Atlética USP",
    organizerSlug: "atletica-usp",
    tier: "verificado",
    theme: "Ressaca",
  },
  {
    id: "16",
    slug: "mack-back-to-school",
    name: "Back to School Mack",
    university: "Mackenzie",
    category: "universitaria",
    date: "2026-02-22",
    location: "Espaço das Américas",
    address: "R. Tagipuru, 795",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1600&q=80",
    price: 5500,
    votes: 887,
    rating: 4.4,
    attendees: 1100,
    tags: ["estudante", "funk", "hits"],
    description: "Volta às aulas com a festa mais esperada da Mack. Três pistas e DJs do funk paulista.",
    organizer: "Atlética Mackenzie",
    organizerSlug: "atletica-mackenzie",
    tier: "verificado",
    theme: "School",
  },
  {
    id: "17",
    slug: "insper-formatura",
    name: "Insper Formatura 2026",
    university: "Insper",
    category: "universitaria",
    date: "2026-04-05",
    location: "KTT2",
    address: "Av. Pres. Juscelino Kubitschek, 360",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1600&q=80",
    price: 22000,
    votes: 1147,
    rating: 4.9,
    attendees: 800,
    tags: ["formatura", "premium", "open"],
    description: "Festa de formatura oficial do Insper. Open premium, line-up internacional e estrutura blacktie.",
    organizer: "Liga Insper",
    organizerSlug: "liga-insper",
    tier: "oficial",
    theme: "Formatura",
  },
  {
    id: "18",
    slug: "espm-marketing-night",
    name: "Marketing Night ESPM",
    university: "ESPM",
    category: "universitaria",
    date: "2026-04-19",
    location: "Cine Joia",
    address: "Pça. Carlos Gomes, 82",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1600&q=80",
    price: 4500,
    votes: 612,
    rating: 4.5,
    attendees: 600,
    tags: ["criativo", "indie", "house"],
    description: "Festa de identidade forte. ESPM trazendo o melhor da cena indie com curadoria de comunicação.",
    organizer: "Atlética ESPM",
    organizerSlug: "atletica-espm",
    tier: "verificado",
    theme: "Indie",
  },
  {
    id: "19",
    slug: "puc-noite-cultural",
    name: "Noite Cultural PUC",
    university: "PUC-SP",
    category: "universitaria",
    date: "2026-04-12",
    location: "Sesc Pinheiros",
    address: "R. Paes Leme, 195",
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=1600&q=80",
    price: 3500,
    votes: 543,
    rating: 4.7,
    attendees: 800,
    tags: ["cultural", "samba", "alternativo"],
    description: "PUC abrindo a temporada com show ao vivo, samba de raiz e DJs alternativos.",
    organizer: "Atlética PUC",
    organizerSlug: "atletica-puc",
    tier: "verificado",
    theme: "Cultural",
  },

  // ===== CLUBS =====
  {
    id: "6",
    slug: "warung-night-vila-madalena",
    name: "Warung Night",
    university: "Vila Madalena",
    category: "club",
    date: "2026-05-09",
    location: "Warung SP",
    address: "Rua Aspicuelta, 180 - Vila Madalena",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1600&q=80",
    price: 18000,
    votes: 980,
    rating: 4.8,
    attendees: 1800,
    tags: ["techno", "house", "underground"],
    description:
      "A noite de quinta mais badalada da Vila. Line-up internacional, sistema de som premium e a galera mais antenada de SP.",
    organizer: "Warung",
    organizerSlug: "warung-sp",
    tier: "oficial",
    theme: "Underground",
  },
  {
    id: "7",
    slug: "audio-saturday",
    name: "Audio Saturday",
    university: "Barra Funda",
    category: "club",
    date: "2026-05-16",
    location: "Audio Club",
    address: "Av. Francisco Matarazzo, 694",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&q=80",
    price: 14000,
    votes: 876,
    rating: 4.7,
    attendees: 2500,
    tags: ["techno", "headliner", "club"],
    description:
      "Headliner internacional toda semana. O sábado oficial da Barra Funda com a estrutura de club mais completa da cidade.",
    organizer: "Audio Club",
    organizerSlug: "audio-club",
    tier: "oficial",
    theme: "Resident",
  },
  {
    id: "8",
    slug: "d-edge-resident",
    name: "D-Edge Resident",
    university: "Barra Funda",
    category: "club",
    date: "2026-05-16",
    location: "D-Edge",
    address: "Al. Olga, 170 - Barra Funda",
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=1600&q=80",
    price: 10000,
    votes: 721,
    rating: 4.7,
    attendees: 800,
    tags: ["techno", "minimal", "underground"],
    description:
      "O reduto techno mais fiel de São Paulo. Line-up curado pelos residentes do D-Edge — só os melhores.",
    organizer: "D-Edge",
    organizerSlug: "d-edge",
    tier: "oficial",
    theme: "Underground",
  },
  {
    id: "20",
    slug: "audio-headline-night",
    name: "Audio Headline Night",
    university: "Barra Funda",
    category: "club",
    date: "2026-04-25",
    location: "Audio Club",
    address: "Av. Francisco Matarazzo, 694",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1600&q=80",
    price: 16000,
    votes: 1145,
    rating: 4.8,
    attendees: 2400,
    tags: ["techno", "headliner", "internacional"],
    description: "Edição especial com headliner top 100 DJ Mag. Estrutura ampliada e produção visual especial.",
    organizer: "Audio Club",
    organizerSlug: "audio-club",
    tier: "oficial",
    theme: "Headliner",
  },
  {
    id: "21",
    slug: "audio-resident-after",
    name: "Audio After Hours",
    university: "Barra Funda",
    category: "club",
    date: "2026-04-04",
    location: "Audio Club",
    address: "Av. Francisco Matarazzo, 694",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1600&q=80",
    price: 9000,
    votes: 654,
    rating: 4.5,
    attendees: 1300,
    tags: ["after", "techno", "residentes"],
    description: "Manhãzinha com residentes do Audio. Vai até as 9h da manhã, só pra quem aguenta.",
    organizer: "Audio Club",
    organizerSlug: "audio-club",
    tier: "verificado",
    theme: "After",
  },
  {
    id: "22",
    slug: "d-edge-techno-friday",
    name: "Techno Friday",
    university: "Barra Funda",
    category: "club",
    date: "2026-04-18",
    location: "D-Edge",
    address: "Al. Olga, 170",
    image: "https://images.unsplash.com/photo-1561489413-985b06da5bee?w=1600&q=80",
    price: 11000,
    votes: 689,
    rating: 4.6,
    attendees: 750,
    tags: ["techno", "minimal", "club"],
    description: "Sexta noite mais fiel ao techno minimal em SP. Curadoria autoral dos residentes.",
    organizer: "D-Edge",
    organizerSlug: "d-edge",
    tier: "oficial",
    theme: "Minimal",
  },
  {
    id: "23",
    slug: "warung-sunday-day",
    name: "Warung Sunday Day",
    university: "Vila Madalena",
    category: "club",
    date: "2026-04-13",
    location: "Warung SP",
    address: "Rua Aspicuelta, 180",
    image: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=1600&q=80",
    price: 14000,
    votes: 712,
    rating: 4.7,
    attendees: 1600,
    tags: ["domingo", "house", "open air"],
    description: "Sunday day no Warung — house, terraço aberto e a Vila como pano de fundo.",
    organizer: "Warung",
    organizerSlug: "warung-sp",
    tier: "oficial",
    theme: "Sunday",
  },
  {
    id: "24",
    slug: "fabrique-rap-night",
    name: "Rap Night Fabrique",
    university: "Barra Funda",
    category: "club",
    date: "2026-04-26",
    location: "Fabrique Club",
    address: "R. Barra Funda, 1071",
    image: "https://images.unsplash.com/photo-1551655510-555dc3be8633?w=1600&q=80",
    price: 7000,
    votes: 531,
    rating: 4.6,
    attendees: 1100,
    tags: ["rap", "trap", "hip-hop"],
    description: "Cena rap nacional e internacional na pista mais autoral da Barra Funda.",
    organizer: "Fabrique Club",
    organizerSlug: "fabrique",
    tier: "verificado",
    theme: "Rap",
  },

  // ===== EVENTOS =====
  {
    id: "9",
    slug: "neon-fest-sp-arena",
    name: "NEON Fest SP",
    university: "Aberto",
    category: "evento",
    date: "2026-05-23",
    location: "Allianz Parque",
    address: "Av. Francisco Matarazzo, 1705",
    image: "https://images.unsplash.com/photo-1496843916299-590492c751f4?w=1600&q=80",
    price: 25000,
    votes: 1521,
    rating: 4.9,
    attendees: 18000,
    tags: ["festival", "headliners", "arena"],
    description:
      "O festival eletrônico que pegou SP de jeito. 3 palcos, +12h de música, line-up com headliners internacionais.",
    organizer: "NEON Productions",
    organizerSlug: "neon-productions",
    tier: "oficial",
    theme: "Festival",
  },
  {
    id: "10",
    slug: "lollapalooza-after-party",
    name: "Lolla After",
    university: "Aberto",
    category: "evento",
    date: "2026-05-24",
    location: "Cine Joia",
    address: "Pça. Carlos Gomes, 82",
    image: "https://images.unsplash.com/photo-1496843916299-590492c751f4?w=1600&q=80",
    price: 11000,
    votes: 689,
    rating: 4.8,
    attendees: 600,
    tags: ["after", "indie", "alternativo"],
    description:
      "A after oficial do Lollapalooza. DJs surpresa do festival e ambiente intimista no Cine Joia.",
    organizer: "T4F",
    organizerSlug: "t4f",
    tier: "oficial",
    theme: "After",
  },
  {
    id: "11",
    slug: "sambafest-vila-olimpia",
    name: "SambaFest VO",
    university: "Aberto",
    category: "evento",
    date: "2026-05-25",
    location: "Villa Mix VO",
    address: "Av. Pres. Juscelino Kubitschek, 1830",
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1600&q=80",
    price: 9000,
    votes: 612,
    rating: 4.6,
    attendees: 1500,
    tags: ["samba", "pagode", "happy hour"],
    description:
      "Pagode 90, samba de raiz e o melhor do happy hour de quarta. SP samba style.",
    organizer: "Villa Mix",
    organizerSlug: "villa-mix",
    tier: "verificado",
    theme: "Pagode",
  },
  {
    id: "25",
    slug: "neon-summer-edition",
    name: "NEON Summer Edition",
    university: "Aberto",
    category: "evento",
    date: "2026-02-15",
    location: "Jockey Club",
    address: "Av. Lineu de Paula Machado, 1263",
    image: "https://images.unsplash.com/photo-1496843916299-590492c751f4?w=1600&q=80",
    price: 28000,
    votes: 1342,
    rating: 4.7,
    attendees: 14000,
    tags: ["festival", "verão", "headliners"],
    description: "Edição de verão do NEON Fest. Open air, 8h de festival, line-up internacional curado.",
    organizer: "NEON Productions",
    organizerSlug: "neon-productions",
    tier: "oficial",
    theme: "Summer Festival",
  },
  {
    id: "26",
    slug: "mamba-edicao-aniversario",
    name: "Mamba Negra · 10 Anos",
    university: "Aberto",
    category: "evento",
    date: "2026-04-05",
    location: "Galpão MN",
    address: "R. Cruzeiro, 200 - Barra Funda",
    image: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=1600&q=80",
    price: 12000,
    votes: 1089,
    rating: 4.9,
    attendees: 2000,
    tags: ["underground", "techno", "edição-marca"],
    description: "Edição de 10 anos da Mamba Negra. Line-up secreto, residentes históricos e produção autoral.",
    organizer: "Mamba Negra",
    organizerSlug: "mamba-negra",
    tier: "oficial",
    theme: "Aniversário",
  },

  // ===== RAVES =====
  {
    id: "12",
    slug: "tribe-rave-interlagos",
    name: "Tribe Rave",
    university: "Aberto",
    category: "rave",
    date: "2026-05-30",
    location: "Galpão Interlagos",
    address: "Av. Interlagos, 4400",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=1600&q=80",
    price: 13000,
    votes: 754,
    rating: 4.7,
    attendees: 3000,
    tags: ["rave", "trance", "outdoor"],
    description:
      "Rave de 14h direto. Open air, decoração imersiva e som premium. Só pra quem tá pra cima.",
    organizer: "Tribe Collective",
    organizerSlug: "tribe-collective",
    tier: "oficial",
    theme: "Open Air",
  },
  {
    id: "27",
    slug: "tribe-spring-equinox",
    name: "Tribe Spring Equinox",
    university: "Aberto",
    category: "rave",
    date: "2026-03-22",
    location: "Sítio Cantareira",
    address: "Estr. Mun. Cantareira, km 12",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80",
    price: 14500,
    votes: 821,
    rating: 4.8,
    attendees: 2200,
    tags: ["rave", "psy", "outdoor"],
    description: "Edição de equinócio da Tribe. 18h de rave em meio à natureza, decoração imersiva e psy trance.",
    organizer: "Tribe Collective",
    organizerSlug: "tribe-collective",
    tier: "oficial",
    theme: "Equinox",
  },
];

export const testimonials = [
  {
    name: "Beatriz Alves",
    university: "USP - Direito",
    text: "Nunca mais perdi festa boa. O ranking em tempo real é viciante e sempre acerta.",
    avatar: "from-violet-500 to-fuchsia-500",
  },
  {
    name: "Lucas Ferraz",
    university: "Insper - Administração",
    text: "Virou ritual do grupo: abrir o PartyRank na quinta pra ver onde rolar no fim de semana.",
    avatar: "from-pink-500 to-orange-500",
  },
  {
    name: "Marina Costa",
    university: "FGV - Economia",
    text: "A lista de fornecedores e o dashboard PRO salvaram nossa atlética. Economizamos 30% nos custos.",
    avatar: "from-cyan-500 to-blue-500",
  },
  {
    name: "João Paulo Martins",
    university: "Mackenzie - Publicidade",
    text: "Compro ingresso direto no app. Sem filas, sem cambistas, sem estresse.",
    avatar: "from-emerald-500 to-teal-500",
  },
];

export const stats = [
  { label: "festas ranqueadas", value: "500+" },
  { label: "casas e clubs", value: "60+" },
  { label: "universidades", value: "50+" },
  { label: "ingressos vendidos", value: "R$2M+" },
];
